// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLescfwZy_mjgrTrYTirSrUiNa8WQNoFU',
    appId: '1:499946725146:web:7aca1fbf4672d934bd16a3',
    messagingSenderId: '499946725146',
    projectId: 'flutter-chat-app-5f27c',
    authDomain: 'flutter-chat-app-5f27c.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5f27c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDAmnNrix_QUX9itEXBhrR07h7KbrIWs',
    appId: '1:499946725146:android:93ea6d8aef2906d6bd16a3',
    messagingSenderId: '499946725146',
    projectId: 'flutter-chat-app-5f27c',
    storageBucket: 'flutter-chat-app-5f27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJT3LLFeCfkL6DwP8YrKR9wUUOJeF3FUg',
    appId: '1:499946725146:ios:7682ae932f0d4efbbd16a3',
    messagingSenderId: '499946725146',
    projectId: 'flutter-chat-app-5f27c',
    storageBucket: 'flutter-chat-app-5f27c.appspot.com',
    iosClientId: '499946725146-mj79qv9n47lsifm8eets7p3ggbbfa9ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJT3LLFeCfkL6DwP8YrKR9wUUOJeF3FUg',
    appId: '1:499946725146:ios:7682ae932f0d4efbbd16a3',
    messagingSenderId: '499946725146',
    projectId: 'flutter-chat-app-5f27c',
    storageBucket: 'flutter-chat-app-5f27c.appspot.com',
    iosClientId: '499946725146-mj79qv9n47lsifm8eets7p3ggbbfa9ov.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
